export interface Image {
  id: number,
  documentId: string,
  name: string,
  alternativeText: null | string,
  caption: null,
  width: number,
  height: number,
  formats: null,
  hash: string,
  ext: string,
  mime: string,
  size: number,
  url: string,
  previewUrl: null,
  provider: string,
  provider_metadata: null,
  createdAt: string,
  updatedAt: string,
  publishedAt: string,
  locale: null
}
